# Generated by Django 4.2.3 on 2023-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_propietario_alter_departamento_edificio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='costo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nro_cuartos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Público', 'Público'), ('Negocio', 'Negocio')], max_length=30),
        ),
    ]
