# Generated by Django 4.2.3 on 2023-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_departamento_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
